### PR TITLE
Add-max-file-size

### LINKED ISSUE #180: File Restrictions Should Be Displayed Within Upup
image

Similarly, how it is done here:
image

### LINKED ISSUE #182: Add File size restriction

### PR DESCRIPTION
**Pull request by MohamedBechirMejri**
Fixes #180 #182 

image

### CODE REVIEW

**Comment by bassem97** [comment]
@MohamedBechirMejri  i think that the new line should be on top of upup component not down with the meta infos , what you think ?

**Comment by bassem97** [comment]
Somewhere right here : 

@AminDhouib @MohamedBechirMejri

**Comment by AminDhouib** [comment]
@bassem97 I think bottom works better just like how uppy does it

**Comment by bassem97** [comment]
> @bassem97 I think bottom works better just like how uppy does it 

Okay, that works too

**Comment by MohamedBechirMejri** [comment]
> @MohamedBechirMejri i think that the new line should be on top of upup component not down with the meta infos , what you think ?

yup I thought of that too

**Comment by bassem97** [comment]
> > @MohamedBechirMejri i think that the new line should be on top of upup component not down with the meta infos , what you think ?
> 
> yup I thought of that too

i thought that down below should be upup version and powered by uNotes only better than adding the line between , but @AminDhouib  want it like that .

**Review by bassem97 — APPROVED** [review]

**Comment by bassem97** [comment]
@MohamedBechirMejri Great job !

**Pull request merged**
